version: '3.8'

services:
  autofirma-app:
    build: .
    container_name: autofirma-container
    ports:
      - "8081:5001"
    volumes:
      - ./signed_docs:/app/signed_docs
    restart: always
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
